# Generated by Django 3.2.9 on 2022-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
                ('product_desc', models.CharField(max_length=400)),
                ('product_quantity', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
