# Generated by Django 3.2.9 on 2022-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.IntegerField(default=''),
        ),
    ]
